#!/bin/bash
mkcd() { mkdir -p "$@" && cd "$_"; }
scratch() { mkdir -p "/tmp/scratchfolder" && cd "/tmp/scratchfolder" }
sman() { curl cht.sh/$1 }
bw() { /usr/bin/bw --session $(cat ~/.bwsession) $@ }
okctl() { $(ovm current -p) $@ }
netup() { sudo netctl start $1 && sudo netctl wait-online $1 }
passgen() { pwgen -sync $1 | cut -d' ' -f1 | wl-copy -n }

##################################################
##### Helm
##################################################
#h() {
#  # Gotten from Yngvar Kristiansen
#  CURRENT_NAMESPACE=`kubectl config view --minify --output 'jsonpath={..namespace}'`
#  echo Using namespace for helm: $CURRENT_NAMESPACE
#  helm --tiller-namespace=$CURRENT_NAMESPACE $@
#}
h() {
  CURRENT_NAMESPACE=`kubectl config view --minify --output 'jsonpath={..namespace}'`
  echo Using namespace for helm: $CURRENT_NAMESPACE
  /usr/bin/helm --namespace=$CURRENT_NAMESPACE $@
}

##################################################
##### Kubernetes
##################################################
#alias kset2="export KUBECONFIG=~/.kube/configs/$1.yaml"
kset() {
  export KUBECONFIG=~/.kube/configs/$1.yaml
}
ksethere() {
	export KUBECONFIG=${PWD}/kubeconfig.yaml
}
knset() {
  export KUBENAMESPACE=$1
}

##################################################
##### Docker
##################################################
prunedocker() {
	docker stop $(docker ps -q) &> /dev/null # Stops all running containers
	docker rm $(docker ps -aq)  &> /dev/null # Removes all containers
	docker rmi -f $(docker images -aq) &> /dev/null # Removes all images
	docker system prune --volumes # Removes most docker data
}

##################################################
##### Git
##################################################
gdf() {
	if [ -z "$1" ]; then
		    echo "usage: $0 number_of_commits"
	fi

	git diff --name-only HEAD~$1 HEAD | cat
}

yolo() {
	current=`git branch --show-current`

	if [[ "${current}" == "master" ]]; then
		echo "careful! no yoloing on master"

		return 1
	fi

	if [[ "${current}" == "main" ]]; then
		echo "careful! no yoloing on main"

		return 1
	fi

	echo "LEEEEEEROY"

	git push -f
}

##################################################
##### AWS
##################################################
profile-select() {
    export AWS_PROFILE=$(aws configure list-profiles | fzf)
}

##################################################
##### Port forwarding
##################################################
ksyncthing() {
	NAME=$(kubectl -n personal get pods | grep syncthing | cut -d' ' -f1)

	kubectl -n personal port-forward ${NAME} 8000:8384
}

kargocd() {
	kubectl -n argocd port-forward svc/argocd-server 8000:443
}

gwc() {
    targetDir=$(basename $1 | cut -d'.' -f1)

    mkdir -p $targetDir
    cd $targetDir

    git clone --bare $1 .bare
    echo "gitdir: ./.bare" > .git
}

_set-monitor-profile() {
    printf "Link $1 monitor setup"
    rm ~/.config/sway/config.d/monitor && ln ~/.config/sway/monitor-setups/$1 ~/.config/sway/config.d/monitor
    printf " ✅\n"
}

_set-default-audio-sink() {
    printf "Set default audio sink to $1"
    pactl set-default-sink $1
    printf " ✅\n"
}

_set-netctl-profile() {
    printf "Activate netctl profile $1"
    sudo netctl start $1
    printf " ✅\n"
}

activate-profile() {
    case $1 in
        "laptop")
            _set-monitor-profile laptop
            _set-default-audio-sink alsa_output.pci-0000_00_1f.3.analog-stereo
            ;;
        "home")
            _set-netctl-profile sanita
            _set-monitor-profile home-office
            _set-default-audio-sink alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo
            ;;
        "work")
            _set-netctl-profile origo
            _set-monitor-profile work
            _set-default-audio-sink alsa_output.pci-0000_00_1f.3.analog-stereo
            sudo systemctl start bluetooth
            ;;
        *)
            echo "Unknown profile $1"
            ;;
    esac
}

profilectl() {
    case $1 in
        "set")
            activate-profile $2
            ;;
    esac
}
